name: Deploy Hugo Site to Azure

on:
  push:
    branches:
      - Master  # Trigger deployment on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from GitHub

    - name: Set up Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.118.2/hugo_0.118.2_Linux-64bit.tar.gz
        tar -xzf hugo_0.118.2_Linux-64bit.tar.gz
        sudo mv hugo /usr/local/bin/

    - name: Build Hugo site
      run: hugo --minify  # Build the static site into the 'public' directory

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: <MyWebApp1234>  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Azure publish profile secret
        package: ./public  # The 'public' folder contains the generated static files
